### PR TITLE
Adapt to Bankscrap 2

### PR DESCRIPTION
**Pull request by zenitraM**
This library wasn't working properly with the latest Bankscrap, so I did some changes to fix it:

- 🤑 Money objects with currency returned everywhere
- 🏦 `Connection` object unified with `Bank` and little changes to adapt to Bankscrap 2 interfaces
- 👮 Some Rubocop warnings fixed
- 👀 README updated to current Bankscrap CLI

### CODE REVIEW

**Comment by raulmarcosl** [comment]
Thanks for the PR! None of us have an Openbank account, so it has been difficult to maintain this adapter.

I have reviewed the code and it looks fantastic, congrats! If you say it works is ready to merge. Only one small thing: I saw two TODOs regarding the lack of `operation_date` in transactions, so I have added them in `bankscrap` gem. I just released the `2.0.4` version that supports both `effective_date` and `operation_date`, so it would be great to use them 🙂

**Review by raulmarcosl — APPROVED** [review]

**Comment by zjuanma** [comment]
I had this plugin updated to bankscrap 2 in my local  master branch , tomorrow I push it to origin. 
I had Santander plugin updated too.

**Comment by raulmarcosl** [comment]
@zjuanma Please, don't push directly to origin master, you are going to generate a lot of conflicts with this PR. Instead, it would be better to have a different PR with your changes to review the code and see the differences with @zenitraM's code, and we can discuss which one merge.

**Comment by javiercr** [comment]
@zenitraM and @zjuanma thank you very much for this!

I've reviewed both PRs and they seem to have similar changes. @raulmarcosl and I we've decided to merge this because it includes changes to the readme and a few interesting comments (like [this](https://github.com/bankscrap/bankscrap-openbank/pull/1/files#diff-04971c44b57c6afbbbad405174aa02ccR70)), but in any case @zjuanma kudos to you for working on this one too 🎉!

I'm gonna publish it to rubygems too.

Are you guys planning to maintain this gem? We got a slack channel and it would be nice to have you around to discuss future work on Bankscrap.

**Comment by javiercr** [comment]
Here it is:
https://rubygems.org/gems/bankscrap-openbank

If you have a rubygems account give me your email address and I'll ad you as owners.

**Pull request merged**
